apiVersion: v1
kind: Service
metadata:
  name: aspnetcore-customerservice
  labels:
    app: aspnetcorecustomerapp
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: aspnetcorecustomerapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcorecustomerapp-v1
spec:
  selector:

    matchLabels:

      app: aspnetcorecustomerapp
  replicas: 1
  template:
    metadata:
      labels:
        app: aspnetcorecustomerapp
        version: v1
    spec:
      containers:
      - name: aspnetcorecustomerapp
        image: eswaribala/ecommerceboarepo:kubecustomerapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:

            - name: ASPNETCORE_ENVIRONMENT

              value: DEVELOPMENT

            - name: SQLSERVER_CONNECTIONSTRING

              value: "Server=Server=host.docker.internal,1433;Database=BoaCustomerDB;User ID=sa;Password=Vignesh@95;MultipleActiveResultSets=true"